name: "Push to dev"
on:
  push:
    branches: [ "dev" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: CI with dev-server
        uses: appleboy/ssh-action@master
        with:
          host: web-devserver.ru
          port: 22
          username: maximenko
          key: ${{secrets.SSH_PRIVATE_KEY_DEV}}
          script: |
            cd ~/projects/bitrixProjects/alexprom/deploy
            sh update.sh